[package]
name = "cargo-results"
version = "0.6.2"
authors = ["Connor Wood <connorwood71@gmail.com"]
keywords = ["test", "cargo"]
license = "MIT"
repository = "https://github.com/CWood1/cargo-results"
description = "Converts cargo test output into a vec of suites"

[dependencies]
nom = "3.2.1"
